### ISSUE TITLE
US-5: Detailed CAD-AiD Model Results

### ISSUE THREAD

**Issue by magnusgiverin** [kartAI/ntnu-kpro-ai-assistant#19]
As an application approver, I want to see the results of the CADAiD model, so that I can discern any deficiencies in the application and ensure all necessary documents meet the required standards.

**Linked issues:**
- [x] #20

**Acceptance criteria:**
- [x] The results page for CAD-AiD should display status indicators next to each document:
- [x] Green check: for documents that are complete and meet requirements.
- [ ] Orange warning: for documents that are present but contain deficiencies.
- [x] Red cross: for missing documents.
