### ISSUE TITLE
US-1: Overview of applications

### ISSUE THREAD

**Issue by magnusgiverin** [kartAI/ntnu-kpro-ai-assistant#2]
As an application approver, I want to have an overview of all the applications I can approve, with the ability to sort and filter these applications based on metrics such as number of errors and approval complexity, 
So that I can efficiently process applications in priority order.

**Linked issues:**
- [x] #3
- [x] #4
- [x] #30
- [x] #35

**Acceptance criteria:**
- [ ] The glanceable information contains application ID, date of submission, complexity, status, and address.
- [ ] The dashboard should contain buttons which can sort and filter the data based on complexity and number of errors.
- [ ] There should be a button on each row (with applications) where the user can click approve or reject immediately
