### ISSUE TITLE
US-7: Indication of status for applications based on AI models

### ISSUE THREAD

**Issue by andreaslhjulstad** [kartAI/ntnu-kpro-ai-assistant#23]
As an application approver, I want a status indication for applications with obvious deficiencies to be clearly marked,
so that I can easily identify applications that need to be returned or require further attention.

**Linked issues:**
- [ ] #24
- [ ] #25

**Acceptance criteria:**
- [x] The overview of applications should have a column for status that shows if it has deficiencies or is ready to be approved. There should be three different statuses:
  - “Fullført” - Green check
  - "Noen mangler" - Orange warning sign
  - "Betydelige mangler" - Red X
- [x] The status indication aggregates results from the models and displays it as a simple icon
- [x] When the user hovers over the indication, they are presented with a more detailed view of what is missing.
